name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # 每天UTC时间0点运行
  workflow_dispatch:      # 允许手动触发
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: .github/snake/github-snake.svg, .github/snake/github-snake-dark.svg?palette=github-dark
          
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/snake
          publish_branch: output
          keep_files: true
          force_orphan: true
